package com.hanamiLink.utils;


public enum EBMsgType{

	BLE_EXCEPTION_OFF(1),

	BLE_ISENABLE_YES(2),

	BLE_ISENABLE_NO(3),

	AB_FM_REFRESH_RADIOS(1000),//刷新电台列表
	AB_FM_REFRESH_RADIOINFO(1001),//刷新电台信息
	AB_FM_REFRESH_SCAN_STATUS(1002),//搜台 开关状态

	AB_MAIN_SUPPORTED_FUNCTION(2000),
	AB_MAIN_TO_FM(2001),
	AB_MAIN_TO_U(2002),//进入u盘
	AB_MAIN_TO_TFCARD(2003),//进入存储卡
	AB_MAIN_TO_AUX(2004),

	AB_MAIN_TO_BT(2005),//进入BT模式
	AB_MAIN_TO_DEFAULT(2006),//返回到Main

	AB_REFRESH_MUSICS(3004),//刷新UDisk and SDCard 的music列表

	AB_REFRESH_MUSIC_INFO(3005),//刷新UDisk and SDCard 的music列表

	AB_REFRESH_MUSIC_INFO_1(3006),//刷新UDisk and SDCard 的music列表

	AB_REFRESH_MUSIC_INFO_PLAYINDEX(3007),//当前音乐的位置

	AB_REFRESH_MUSIC_PLAYBACK_MODE(3008),//播放模式和播放状态

	AB_REFRESH_MUSIC_PLAYBACK(3009),//单独播放状态

	AB_REFRESH_MUSIC_PLAYMODE(3010),//单独播放模式


	AB_RECORD_STATUS(4000),//录音状态:录音中，
	AB_RECORD_TIME(4001),//录音时间
	AB_RECORD_PLAY_STATUS(4002),
	AB_RECORD_PLAY_TIME(4003),

	AB_AUX_PLAY_AND_RECORD_STATUS(5000),

	AB_VOLUME_INFO(6000),
	AB_VOLUME_BASS_INFO(6001),
	AB_VOLUME_TREBLE_INFO(6002),


	AB_MIC_VOLUME_INFO(6003),
	AB_MIC_VOLUME_BASS_INFO(6004),
	AB_MIC_VOLUME_TREBLE_INFO(6005),

	AB_VOLUME_EQ_INDEX_INFO(6006),



	AB_REFRESH_BT_MUSIC_LIST(7000),//刷新BT的music列表
	AB_REFRESH_BT_MUSIC_INFO(7001),//刷新BT的music列表

	AB_REFRESH_LIGHT_INFO(8000),//灯控


	AB_REFRESH_TIMER_INFO(9000),//定时界面刷新

;

	private int iNum = 0;

	/* 构造器，记住喇，必须是私有的~ */
	private EBMsgType(int iNum) {
		this.iNum = iNum;
	}

	/* 用这个方法代替ordinal()方法，安全，专业，包退包换~ */
	public int toNumber() {
		return this.iNum;

	}



}
